name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD }}
        # Container registry server url
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: 
        docker pull ${{ secrets.ACR_LOGIN_SERVER }}/acs-oai-asynclatest || true;
        docker build . --file Docker/Dockerfile --cache-from ${{ secrets.ACR_LOGIN_SERVER }}/acs-oai-asynclatest --tag ${{ secrets.ACR_LOGIN_SERVER }}/acs-oai-async$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ${{ secrets.ACR_LOGIN_SERVER }}/acs-oai-asynclatest:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ${{ secrets.ACR_LOGIN_SERVER }}/acs-oai-asynclatest:latest;      
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/acs-oai-async$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/acs-oai-asynclatest
        
